name: CI Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Test building on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest] # , windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: install apache (ubuntu)
      if: runner.os == 'Linux'
      run: sudo apt-get install apache2 apache2-dev
    - name: make
      run: make
      working-directory: ./mod_authnz_external
    - name: make install
      run: sudo make install
      working-directory: ./mod_authnz_external
    - name: restart apache (ubuntu)
      if: runner.os == 'Linux'
      run: sudo service apache2 restart
    - name: restart apache (macos)
      if: runner.os == 'macOS'
      run: sudo brew services restart httpd
