name: CI Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Test building on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
      working-directory: ./mod_authnz_external
    - name: make
      run: make
      working-directory: ./mod_authnz_external
    - name: make check
      run: make check
      working-directory: ./mod_authnz_external
    - name: make distcheck
      run: make distcheck
      working-directory: ./mod_authnz_external
